### ISSUE TITLE
Sauce options are used in combination with incorrect capability names

### ISSUE THREAD

**Issue by wswebcreation** [saucelabs-training/demo-python#14]
**Issue:**
Sauce Labs is using `sauce:options` to tell the VM's to start a W3C session, but the rest of the capabilities need the have the proper W3C names (See also https://wiki.saucelabs.com/display/DOCS/W3C+Capabilities+Support).

The capabilities in this file are not correct, https://github.com/saucelabs-training/demo-python/blob/master/selenium-examples/pytest/conftest.py#L27

**Comment by joshmgrant** [comment]
Great catch here @wswebcreation! I've opened a PR to address this.
