### ISSUE TITLE
Argument "driver" passed to pytest_runtest_protocol not found in hookspec

### ISSUE THREAD

**Issue by bralles** [saucelabs-training/demo-python#27]
Hi. I dont believe this is working. I copied the code and pasted it on a conftest.py file. I tried running it using my own saucelabs credentials and received a PluginValidation error: 

File "c:\users\asalas008\desktop\vscode\awt\awt\.venv\lib\site-packages\pluggy\manager.py", line 252, in _verify_hook
    raise PluginValidationError(
pluggy.manager.PluginValidationError: Plugin 'C:\\Users\\asalas008\\Desktop\\VSCode\\awt\\awt\\conftest.py' for hook 'pytest_runtest_protocol'
hookimpl definition: pytest_runtest_protocol(item, nextitem, driver)
Argument(s) {'driver'} are declared in the hookimpl but can not be found in the hookspec

What could I be doing wrong? I pretty much copied and paste the code.

**Comment by bralles** [comment]
Nevermind. It looks like the problem is that I named the file conftest.py.

**Comment by joshmgrant** [comment]
Thank you for the interest in this repo! Let me know if you have any other questions or issues!
